name: Build

on: [push, workflow_dispatch]

jobs:
  Build:
    name: Mac OS X
    runs-on: macos-latest 

    steps:
    - uses: actions/checkout@main
    - name: Configure
      run: |
        cmake -B build -C cmake_checks_cache.txt
        
    - name: Build
      run: |
        cmake --build build/ --parallel 4
        
    - name: Upload
      uses: actions/upload-artifact@main
      with:
        path: build/libSDL2-2.0.0.dylib
                
